name = "Minilog Hugo"
license = "MIT"
licenselink = "https://github.com/gethugothemes/minilog-hugo/blob/master/LICENSE"
description = "Minilog is a free Blog theme based on Bootstrap and powered by Hugo. It fits for Blog, Lifestyle, Travel, Food, websites. It is modern, and clean look with Dark Mode."

homepage = "https://github.com/gethugothemes/minilog-hugo/"
demosite = "https://demo.gethugothemes.com/minilog/"
tags = ['blog', 'light', 'bootstrap', "dark", 'contact-form']
features = ['responsive']
min_version = "0.88.1"

[author]
name = "gethugothemes"
homepage = "https://gethugothemes.com/"